import type {DpoObservation,McstRecord,OutputRow} from './types';
import {cleanSourceText,compareIdentity,normaliseMcstNumber,normaliseUen} from './normalise';
const BATCH=75;
export async function upsertMcstRecords(db:D1Database,rs:McstRecord[]){for(let i=0;i<rs.length;i+=BATCH){await db.batch(rs.slice(i,i+BATCH).map(r=>db.prepare(`INSERT INTO mcst_records(mcst_no,estate_name,uen,source,source_estate_name,updated_at) VALUES(?,?,?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(mcst_no,estate_name,source) DO UPDATE SET uen=excluded.uen,source_estate_name=excluded.source_estate_name,updated_at=CURRENT_TIMESTAMP`).bind(r.mcst_no,r.estate_name,r.uen,r.source,r.source_estate_name)));}}
export async function replaceLookupJobs(db:D1Database){await db.prepare('DELETE FROM lookup_jobs').run();await db.prepare(`INSERT INTO lookup_jobs(mcst_no,status) SELECT DISTINCT mcst_no,'pending' FROM mcst_records WHERE source='BCA'`).run();}
export async function getNextLookupJobs(db:D1Database,limit:number){const r=await db.prepare(`SELECT m.id,m.mcst_no,m.estate_name,m.uen,m.source,m.source_estate_name FROM lookup_jobs j JOIN mcst_records m ON m.id=(SELECT m2.id FROM mcst_records m2 WHERE m2.mcst_no=j.mcst_no AND m2.source='BCA' ORDER BY m2.updated_at DESC,m2.id DESC LIMIT 1) WHERE j.status='pending' ORDER BY CAST(j.mcst_no AS INTEGER) LIMIT ?`).bind(limit).all<McstRecord>();return r.results??[];}
export async function getLookupProgress(db:D1Database){const r=await db.prepare(`SELECT COUNT(*) total,SUM(status='pending') pending,SUM(status='processing') processing,SUM(status='completed') completed,SUM(status='failed') failed FROM lookup_jobs`).first<any>();return{total:Number(r?.total??0),pending:Number(r?.pending??0),processing:Number(r?.processing??0),completed:Number(r?.completed??0),failed:Number(r?.failed??0)};}
export async function markLookupProcessing(db:D1Database,m:string){await db.prepare(`UPDATE lookup_jobs SET status='processing',attempts=attempts+1,last_error=NULL,started_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE mcst_no=? AND status='pending'`).bind(m).run();}
export async function markLookupPending(db:D1Database,m:string,e=''){await db.prepare(`UPDATE lookup_jobs SET status='pending',last_error=?,started_at=NULL,completed_at=NULL,updated_at=CURRENT_TIMESTAMP WHERE mcst_no=?`).bind(e,m).run();}
export async function markLookupCompleted(db:D1Database,m:string){await db.prepare(`UPDATE lookup_jobs SET status='completed',last_error=NULL,completed_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE mcst_no=?`).bind(m).run();}
export async function clearExistingDpoResults(db:D1Database,m:string){await db.prepare('DELETE FROM dpo_records WHERE mcst_no=?').bind(m).run();}
async function audit(db:D1Database,a:any){await db.prepare(`INSERT INTO pdpc_lookup_attempts(mcst_no,bca_uen,estate_name,search_type,search_value,outcome,pdpc_organisation_name,pdpc_uen,dpo_name,dpo_email,discrepancy,discrepancy_reason) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)`).bind(a.mcst,a.bcaUen,a.estate,a.type,a.value,a.outcome,a.org,a.pdpcUen,a.name,a.email,a.disc?1:0,a.reason).run();}
export async function saveNoDpoResult(db:D1Database,r:McstRecord,status:string,method:string,value=''){const mcst=normaliseMcstNumber(r.mcst_no),uen=normaliseUen(r.uen),estate=cleanSourceText(r.estate_name),sv=value||(method==='uen'?uen:estate);await db.prepare(`INSERT INTO dpo_records(mcst_no,uen,estate_name,dpo_found,dpo_name,dpo_email,dpo_company,pdpc_organisation_name,pdpc_uen,record_discrepancy,discrepancy_reason,lookup_status,lookup_method,checked_at) VALUES(?,?,?,0,'','','','','',0,'',?,?,CURRENT_TIMESTAMP)`).bind(mcst,uen,estate,status,method).run();await audit(db,{mcst,bcaUen:uen,estate,type:method,value:sv,outcome:status,org:'',pdpcUen:'',name:'',email:'',disc:false,reason:''});}
export async function saveDpoObservations(db:D1Database,r:McstRecord,obs:DpoObservation[],status:string,method:string,value=''){const mcst=normaliseMcstNumber(r.mcst_no),bcaUen=normaliseUen(r.uen),estate=cleanSourceText(r.estate_name),sv=value||(method==='uen'?bcaUen:estate);for(const o of obs){const org=cleanSourceText(o.organisationName),pu=normaliseUen(o.uen),c=compareIdentity({bcaMcstNo:mcst,bcaUen,bcaEstateName:estate,pdpcUen:pu,pdpcEntityName:org});await db.prepare(`INSERT INTO dpo_records(mcst_no,uen,estate_name,dpo_found,dpo_name,dpo_email,dpo_company,pdpc_organisation_name,pdpc_uen,record_discrepancy,discrepancy_reason,lookup_status,lookup_method,checked_at) VALUES(?,?,?,1,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP)`).bind(mcst,bcaUen||pu,estate,cleanSourceText(o.dpoName),cleanSourceText(o.dpoEmail),cleanSourceText(o.dpoCompany),org,pu,c.discrepancy?1:0,c.reason,status,method).run();await audit(db,{mcst,bcaUen,estate,type:method,value:sv,outcome:status,org,pdpcUen:pu,name:cleanSourceText(o.dpoName),email:cleanSourceText(o.dpoEmail),disc:c.discrepancy,reason:c.reason});}}
export async function getOutputRows(db:D1Database):Promise<OutputRow[]>{const r=await db.prepare(`SELECT mcst_no,estate_name,uen,dpo_found,dpo_name,dpo_email,dpo_company,record_discrepancy FROM dpo_records ORDER BY CAST(mcst_no AS INTEGER),id`).all<any>();return (r.results??[]).map(x=>({'MCST#':x.mcst_no,'Estate Name':x.estate_name??'','UEN':x.uen??'','DPO(Y/N)':x.dpo_found?'Y':'N','DPO Name':x.dpo_name??'','DPO Email':x.dpo_email??'','DPO Company':x.dpo_company??'','Record Discrepancy(Y/N)':x.record_discrepancy?'Y':'N'}));}
